spring:
  application:
    name: discodeit
  profiles:
    active: dev # 기본값 dev 프로필 활성화
  jpa:
    open-in-view: false
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always # 항상 스키마 초기화 스크립트 실행
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 커스텀
discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit-files